# Spring properties
spring:
  application:
      name: caas-api
  security:
    username:
    password:

project:
  name: caas-api
  artifactId: caas-api
  description: caas-api management service

management:     # If you set off security...
  security:
    enabled: false

---
spring:
  profiles:
    active: local

logging:
  level:
    ROOT: INFO
  path: classpath:logback-spring.xml
  file: logs/application.log

# HTTP Server
server:
  port: ${PORT:3333}   # HTTP (Tomcat) port

kubernetes:
  adminToken: ADMIN_TOKEN
  api:
    endpoint: KUBE_API_ENDPOINT

---
spring:
  profiles: dev

logging:
  level:
    ROOT: INFO
  path: classpath:logback-spring.xml
  file: logs/application.log

# HTTP Server
server:
  port: ${PORT:3333}   # HTTP (Tomcat) port

kubernetes:
  adminToken: ADMIN_TOKEN
  api:
    endpoint: KUBE_API_ENDPOINT
